#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'action-servers','console_scripts','fibonacci_action_server'
__requires__ = 'action-servers'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('action-servers', 'console_scripts', 'fibonacci_action_server')()
    )
