######################################################
#                 GET SYSTEM FRAME                   #
######################################################

# SUPPORTED_FRAMES
string WORLD  = "world"
string BASE   = "base"
string ELBOW  = "elbow"
string FLANGE = "tfc"
string TCP    = "tcp"
string TARGET = "target"

string     name     # SUPPORTED_FRAMES
string     ref      # SUPPORTED_FRAMES
